drop table if exists permissao cascade;
drop table if exists usuario cascade;
drop table if exists publicacao cascade;
drop table if exists comentario cascade;
drop table if exists curtidas cascade;
drop table if exists amigos cascade;
drop table if exists solicitacao_amizade cascade;
drop table if exists perfil_usuario cascade;


CREATE TABLE usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL unique,
	senha VARCHAR(100) NOT NULL,
	ativo BOOLEAN NOT NULL
);
ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);


CREATE TABLE permissao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL,
	usuario_id BIGINT NOT NULL
);
ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (nome, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;

create table perfil_usuario (
	id bigint generated by default as identity not null,
    descricao text,
	apelido varchar(50) unique,
	idade Integer not null,
	imagem_perfil Text,
	id_usuario bigint not null
);

alter table perfil_usuario add constraint pk_perfil_usuario primary key (id);
alter table perfil_usuario add constraint fk_perfil_usuario_usuario foreign key (id_usuario) references usuario;

create table publicacao (
	id bigint generated by default as identity not null,
    curtidas Integer,
	descricao Text not null,
	data_postagem timestamp not null,
	privado boolean not null,
	imagem_publicacao Text,
	id_usuario bigint not null
);

alter table publicacao add constraint pk_publicacao primary key (id);
alter table publicacao add constraint fk_publicao_usuario foreign key (id_usuario) references usuario;


create table curtidas (
    id_publicacao bigint not null,
    id_usuario bigint not null
);

alter table curtidas add constraint fk_publicacao foreign key (id_publicacao) references publicacao;
alter table curtidas add constraint fk_curtidas foreign key (id_usuario) references usuario;


create table amigos (
	id_usuario1 bigint not null,
	id_usuario2 bigint not null
);

alter table amigos add constraint fk_amigos_id_usuario1 foreign key (id_usuario1) references usuario;
alter table amigos add constraint fk_amigos_id_usuario2 foreign key (id_usuario2) references usuario;

create table solicitacao_amizade (
	id_usuario1 bigint not null,
	id_usuario2 bigint not null
);

alter table solicitacao_amizade add constraint fk_solicitacao_amizade_id_usuario1 foreign key (id_usuario1) references usuario;
alter table solicitacao_amizade add constraint fk_solicitacao_amizade_id_usuario2 foreign key (id_usuario2) references usuario;

create table comentario (
	id bigint generated by default as identity not null,
    data_postagem timestamp not null,
	comentario varchar(512) not null,
	id_publicacao bigint not null,
	id_usuario bigint not null
);

alter table comentario add constraint pk_comentario primary key (id);
alter table comentario add constraint fk_comentario_publicacao foreign key (id_publicacao) references publicacao;
alter table comentario add constraint fk_comentario_usuario foreign key (id_usuario) references usuario;


